
version: '3'
services:
    mysql:
      image: mysql:8.0
      container_name: mysql-server-80
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - .:/application
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD='root'.
        - MYSQL_DATABASE=currency_convert_dbase
        - MYSQL_USER='root'
        - MYSQL_PASSWORD='root'
      ports:
    - "8889:3306"
  website:
    container_name: php72
    image: php_img:latest
    build:
      context: ./
    volumes:
      - /Applications/MAMP/htdocs/Dockerfil/src:/var/www/html/
    ports:
      - 8000:80